name: Run ReSharper CI

on:
  push:
    branches:
      - CiBranche
  pull_request:
    branches:
      - CiBranche

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and install ReSharper CLI
      run: dotnet tool install JetBrains.ReSharper.GlobalTools --tool-path .
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Set your desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Run ReSharper inspections
      run: ./resharperinspect.sh ApiApplication.sln --output=resharper-results.xml
        #dotnet tool install JetBrains.ReSharper.GlobalTools --tool-path .
        #./resharperinspect.sh ApiApplication.sln --output=resharper-results.xml

    - name: Upload ReSharper results
      uses: actions/upload-artifact@v2
      with:
        name: resharper-results
        path: resharper-results.xml


     # - name: Install ReSharper CLI
     #   run:
          #choco install resharper-clt -y
     #     choco install dupfinder -y

    
          
     # - name: ReSharper InspectCode
     #   uses: JetBrains/ReSharper-InspectCode@v0.3
      #  with:
       #   solution: ./ApiApplication.sln
       
     # - name: Run CleanupCode
      #  run: CleanupCode.exe ApiApplication.sln


         

  
