name: Run ReSharper CI

on:
  push:
    branches:
      - CiBranche
  pull_request:
    branches:
      - CiBranche

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
   # - name: Setup .NET
    #  uses: actions/setup-dotnet@v1
     # with:
      #  dotnet-version: '6.0.x'  # Set your desired .NET version

   # - name: Restore dependencies
    #  run: dotnet restore

    - name: Download ReSharper Command Line Tools
      run: |      
        $url = "https://download.jetbrains.com/resharper/dotUltimate.2023.1/JetBrains.ReSharper.CommandLineTools.2023.1.zip"
        $output = "ReSharperCLT.zip"        
        Invoke-WebRequest -Uri $url -OutFile $output      
        Expand-Archive $output -DestinationPath .\ReSharperCLT
       
     
    - name: Run ReSharper inspections
      run: .\resharperclt\inspectcode.exe ApiApplication.sln --output=resharper-results.xml

      
    - name: Upload ReSharper results
      uses: actions/upload-artifact@v2
      with:
        name: resharper-results
        path: resharper-results.xml


    

         

  
