name: Run ReSharper CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Set your desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Run ReSharper inspections
      run: dotnet inspectcode ApiApplication.sln --output=.github/resharper-results.xml

    - name: Upload ReSharper results
      uses: actions/upload-artifact@v2
      with:
        name: resharper-results
        path: .github/resharper-results.xml


     # - name: Install ReSharper CLI
     #   run:
          #choco install resharper-clt -y
     #     choco install dupfinder -y

    
          
     # - name: ReSharper InspectCode
     #   uses: JetBrains/ReSharper-InspectCode@v0.3
      #  with:
       #   solution: ./ApiApplication.sln
       
     # - name: Run CleanupCode
      #  run: CleanupCode.exe ApiApplication.sln


         

  
