# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ReSharper

on:
  push:
    branches: [ "CiBranche" ]
  pull_request:
    branches: [ "CiBranche" ]

jobs:
   Check:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install ReSharper CLI
        run:
          choco install resharper-clt -y
     #     choco install dupfinder -y

      - name: ReSharper InspectCode
        uses: JetBrains/ReSharper-InspectCode@v0.3
        with:
          solution: ./ApiApplication.sln
       
      - name: Run CleanupCode
        run: CleanupCode.exe ApiApplication.sln

  
