name: DockerImage
on:

  pull_request:
    branches: [CiBranche]
    
  push:
    branches: [CiBranche]
 # workflow_dispatch:

jobs:
  build:
    name: docker
    runs-on: windows-latest
 
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Publish ApiApplication
        run: |
          dotnet publish ./ApiApplication/ApiApplication.csproj -c Release -o ./publish
        working-directory: ${{ github.workspace }}

      - name: Archive production artifacts
        run: |
          mkdir artifacts
          cp -r publish/* artifacts/
        working-directory: ${{ github.workspace }}

      - name: Checkout code again to access artifacts
        uses: actions/checkout@v3
        with:
          path: ./deploy
          ref: ${{ github.sha }}

      - name: Create Dockerfile
        run: |
          echo "FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base" >> deploy/Dockerfile
          echo "WORKDIR /app" >> deploy/Dockerfile
          echo "COPY ./ /app/" >> deploy/Dockerfile
          echo "ENTRYPOINT [\"dotnet\", \"Movie-API/ApiApplication.dll\"]" >> deploy/Dockerfile
        working-directory: ${{ github.workspace }}

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t docker.io/aziz12063/movie-api-challenge:${{ github.sha }} ./deploy
          docker push docker.io/aziz12063/movie-api-challenge:${{ github.sha }}
    
      

        
      
