name: DockerImage
on:

  pull_request:
    branches: [CiBranche]
    
  push:
    branches: [CiBranche]
 # workflow_dispatch:

jobs:
  build:
    name: docker
    runs-on: windows-latest
 
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Publish ApiApplication
        run: |
          dotnet publish Movie-API/ApiApplication/ApiApplication.csproj -c Release -o ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: ./publish

      - name: Create Dockerfile
        run: |
          echo "FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base" >> Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "EXPOSE 80" >> Dockerfile
          echo "" >> Dockerfile
          echo "COPY ./published-app ./" >> Dockerfile
          echo "ENTRYPOINT [\"dotnet\", \"ApiApplication.dll\"]" >> Dockerfile

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t movie-api:latest .

      - name: Push Docker image
        run: |
          docker tag movie-api:1.0.0 ${{ secrets.DOCKER_REGISTRY_URL }}/movie-api:1.0.0
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/movie-api:latest

        
      
