name: SonarCloud Test

on:
  push:
    branches:
      - CiBranche  
  pull_request:
    branches:
      - CiBranche

jobs:
  sonarcloud-check:
    runs-on: windows-latest
    
    env:
      MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        organization: "aziz-rahimi"
        project: "aziz12063_Movie-API"
        token: ${{ secrets.SONAR_TOKEN }}

    - name: Setup MSBuild
      run: echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_PATH
  

    - name: Build with MSBuild
      run: msbuild /t:Rebuild

    - name: Run SonarCloud Analysis
      run: msbuild /t:SonarQubeAnalysis
