name: SonarCloud Test

on:
  push:
    branches:
      - CiBranche 
  pull_request:
    branches:
      - CiBranche

jobs:
 
  sonarcloud-check:
    runs-on: self-hosted
    container: mcr.microsoft.com/windows/servercore:ltsc2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      run: echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_PATH

    - name: Setup SonarCloud
      uses: sonarsource/sonar-scanner-msbuild-action@1.0.0
      with:
        entryPoint: MSBuild.SonarQube.Runner.exe
        args: begin /k:"aziz12063_Movie-API" /d:sonar.organization="aziz-rahimi" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" end

    - name: Build with MSBuild
      run: msbuild /t:Rebuild

    - name: Run SonarCloud Analysis
      uses: sonarsource/sonar-scanner-msbuild-action@1.0.0
      with:
        entryPoint: MSBuild.SonarQube.Runner.exe
        args: end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
